### PR TITLE
Make Data logging optional

### PR DESCRIPTION
**Pull request by yannicklamprecht**
This PR is adding a listener which makes datalogging optional

fixes https://github.com/AlbinEriksson/Java-Steam-Controller/issues/1

### CODE REVIEW

**Comment by AlbinEriksson** [comment]
Wow, I can't believe I left that in by mistake. I approve of the `LogListener` class idea, but since it accepts the raw data expressed as a `String`, wouldn't it be better to create a listener which accepts the raw data as a `byte[]`?

**Comment by yannicklamprecht** [comment]
Yeah your right. Let the user decide how to handle the Byte array. Will commit the change tomorrow. Good night

**Comment by AlbinEriksson** [comment]
Approved, but I will make some stylistic changes before I merge to the master branch. Thanks for your contribution!

**Comment by yannicklamprecht** [comment]
Yes that’s a solution I thought of, too. This cleans it up.

**Pull request merged**
